### ISSUE TITLE
v21.2.0.0: Simple model with 4 walls does not open in some IFC viewers

### ISSUE THREAD

**Issue by eibre** [Autodesk/revit-ifc#254]
It looks OK in Solibri, but Areddo and XBIM Xplorer does not open the file which is attached below.

==== 21:02	ERROR	Xbim.WinUI
Error creating geometry context of '\Documents\Project1.ifc'    at Xbim.Geometry.XbimCurve2D.Init(IIfcCurve curve)
   at Xbim.Geometry.XbimCurve2D..ctor(IIfcCurve curve)
   at Xbim.Geometry.XbimGeometryCreator.CreateGrid(IIfcGrid grid)
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.WriteShapeGeometries(XbimCreateContextHelper contextHelper, ReportProgressDelegate progDelegate, IGeometryStoreInitialiser geometryStore, XbimGeometryType geomStorageType)
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext(ReportProgressDelegate progDelegate, Boolean adjustWcs)
   at XbimXplorer.XplorerMainWindow.OpenAcceptableExtension(Object s, DoWorkEventArgs args).

Error creating geometry context of '\Documents\Project1.ifc'    at Xbim.Geometry.XbimCurve2D.Init(IIfcCurve curve)
   at Xbim.Geometry.XbimCurve2D..ctor(IIfcCurve curve)
   at Xbim.Geometry.XbimGeometryCreator.CreateGrid(IIfcGrid grid)
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.WriteShapeGeometries(XbimCreateContextHelper contextHelper, ReportProgressDelegate progDelegate, IGeometryStoreInitialiser geometryStore, XbimGeometryType geomStorageType)
   at Xbim.ModelGeometry.Scene.Xbim3DModelContext.CreateContext(ReportProgressDelegate progDelegate, Boolean adjustWcs)
   at XbimXplorer.XplorerMainWindow.OpenAcceptableExtension(Object s, DoWorkEventArgs args).

Unsupported Curve Type IfcIndexedPolyCurve

[Project1.zip](https://github.com/Autodesk/revit-ifc/files/5675358/Project1.zip)
![image](https://user-images.githubusercontent.com/5968613/101823903-bfa7a680-3b2b-11eb-8133-3f5176c09bd6.png)

**Comment by Moult** [comment]
Possible bug with XBimXplorer? At a brief glance the indexed poly curve looks correct. Here is it opened in the BlenderBIM Add-on.

However what's up with the grids! Why do I see duplicated grids on every level?

Also, the IfcSite "datum" object is incorrectly related with a spatially contained in relationship. I've noticed IfcSite has been commonly misused in Revit this way.

![2020-12-11-092349_910x699_scrot](https://user-images.githubusercontent.com/88302/101837068-9706c780-3b92-11eb-9706-f4649ab0e681.png)

**Comment by AngelVelezSosa** [comment]
It does say: "Unsupported Curve Type IfcIndexedPolyCurve" which implies that the entity just isn't supported.
Grids in IFC are per-level, not per project (unlike in Revit).

"Also, the IfcSite "datum" object is incorrectly related with a spatially contained in relationship. I've noticed IfcSite has been commonly misused in Revit this way." - can you clarify this @Moult ?  I'm closing the original issue.

**Comment by Moult** [comment]
@AngelVelezSosa grids in IFC are per level? Really? I didn't know that. Can you show me where in the documentation it says this? I just checked the page on IfcGrid and IfcBuildingStorey and didn't see anything about that.

To clarify, the IfcSite object `1EH6FudmT63O$f0KliAMRA` has an IfcRelContainedInSpatialStructure, relating an IfcSite to an IfcBuildingStorey. I believe that this is invalid as the spatial containment concept only applies to IfcSpatialElement and an IfcElement. Instead, an IfcRelAggregates should be used.
